///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CosbiomeVentaResponseModelDireccion {
  /*
{
  "tipo": ".",
  "domicilio": ".",
  "colonia": ".",
  "ciudad": ".",
  "estado": ".",
  "codigoPostal": ".",
  "cruces": "."
} 
*/

  String? tipo;
  String? domicilio;
  String? colonia;
  String? ciudad;
  String? estado;
  String? codigoPostal;
  String? cruces;

  CosbiomeVentaResponseModelDireccion({
    this.tipo,
    this.domicilio,
    this.colonia,
    this.ciudad,
    this.estado,
    this.codigoPostal,
    this.cruces,
  });
  CosbiomeVentaResponseModelDireccion.fromJson(Map<String, dynamic> json) {
    tipo = json['tipo']?.toString();
    domicilio = json['domicilio']?.toString();
    colonia = json['colonia']?.toString();
    ciudad = json['ciudad']?.toString();
    estado = json['estado']?.toString();
    codigoPostal = json['codigoPostal']?.toString();
    cruces = json['cruces']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['tipo'] = tipo;
    data['domicilio'] = domicilio;
    data['colonia'] = colonia;
    data['ciudad'] = ciudad;
    data['estado'] = estado;
    data['codigoPostal'] = codigoPostal;
    data['cruces'] = cruces;
    return data;
  }
}

class CosbiomeVentaResponseModelProductosCompra {
  /*
{
  "producto": "LIGHT ABRASION CREAM 100 GR  EUPEEL",
  "precio": "624",
  "cantidad": "1"
} 
*/

  String? producto;
  String? precio;
  String? cantidad;

  CosbiomeVentaResponseModelProductosCompra({
    this.producto,
    this.precio,
    this.cantidad,
  });
  CosbiomeVentaResponseModelProductosCompra.fromJson(
    Map<String, dynamic> json,
  ) {
    producto = json['producto']?.toString();
    precio = json['precio']?.toString();
    cantidad = json['cantidad']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['producto'] = producto;
    data['precio'] = precio;
    data['cantidad'] = cantidad;
    return data;
  }
}

class CosbiomeVentaResponseModel {
  /*
{
  "abono": false,
  "apartado": 0,
  "estatus": "PAGANDO",
  "ENVIO": "NORMAL",
  "peso": "0kg",
  "sucursal": "FEDERALISMO",
  "_id": "67eab8d0dcb54bb464684535",
  "vendedor": "Pablo Rizo",
  "total": 405.6,
  "subTotal": 624,
  "referencia": "",
  "productosCompra": [
    {
      "producto": "LIGHT ABRASION CREAM 100 GR  EUPEEL",
      "precio": "624",
      "cantidad": "1"
    }
  ],
  "numTel": "3319747514",
  "nota": ".",
  "nombreCliente": "Juan Pablo Rizo Quintero",
  "metodoDePago": "",
  "medio": "enExpo",
  "iva": 0,
  "idPedido": "10620PU",
  "idFirebase": "",
  "idCliente": "",
  "horaVenta": "09:46:24",
  "fechaVenta": "03/31/2025",
  "fechaDeEntrega": "2025-03-31",
  "direccion": {
    "tipo": ".",
    "domicilio": ".",
    "colonia": ".",
    "ciudad": ".",
    "estado": ".",
    "codigoPostal": ".",
    "cruces": "."
  },
  "de": "",
  "cargo": 0,
  "autorizado": "",
  "a": "",
  "pagos": "puntoDeVenta",
  "published_at": "2025-03-31T15:46:24.643Z",
  "createdAt": "2025-03-31T15:46:24.655Z",
  "updatedAt": "2025-03-31T15:46:24.655Z",
  "__v": 0,
  "id": "67eab8d0dcb54bb464684535"
} 
*/

  bool? abono;
  int? apartado;
  String? estatus;
  String? ENVIO;
  String? peso;
  String? sucursal;
  String? Id;
  String? vendedor;
  double? total;
  int? subTotal;
  String? referencia;
  List<CosbiomeVentaResponseModelProductosCompra?>? productosCompra;
  String? numTel;
  String? nota;
  String? nombreCliente;
  String? metodoDePago;
  String? medio;
  int? iva;
  String? idPedido;
  String? idFirebase;
  String? idCliente;
  String? horaVenta;
  String? fechaVenta;
  String? fechaDeEntrega;
  CosbiomeVentaResponseModelDireccion? direccion;
  String? de;
  int? cargo;
  String? autorizado;
  String? a;
  String? pagos;
  String? publishedAt;
  String? createdAt;
  String? updatedAt;
  int? _V;
  String? id;

  CosbiomeVentaResponseModel({
    this.abono,
    this.apartado,
    this.estatus,
    this.ENVIO,
    this.peso,
    this.sucursal,
    this.Id,
    this.vendedor,
    this.total,
    this.subTotal,
    this.referencia,
    this.productosCompra,
    this.numTel,
    this.nota,
    this.nombreCliente,
    this.metodoDePago,
    this.medio,
    this.iva,
    this.idPedido,
    this.idFirebase,
    this.idCliente,
    this.horaVenta,
    this.fechaVenta,
    this.fechaDeEntrega,
    this.direccion,
    this.de,
    this.cargo,
    this.autorizado,
    this.a,
    this.pagos,
    this.publishedAt,
    this.createdAt,
    this.updatedAt,
    this.id,
  });
  CosbiomeVentaResponseModel.fromJson(Map<String, dynamic> json) {
    abono = json['abono'];
    apartado = json['apartado']?.toInt();
    estatus = json['estatus']?.toString();
    ENVIO = json['ENVIO']?.toString();
    peso = json['peso']?.toString();
    sucursal = json['sucursal']?.toString();
    Id = json['_id']?.toString();
    vendedor = json['vendedor']?.toString();
    total = json['total']?.toDouble();
    subTotal = json['subTotal']?.toInt();
    referencia = json['referencia']?.toString();
    if (json['productosCompra'] != null) {
      final v = json['productosCompra'];
      final arr0 = <CosbiomeVentaResponseModelProductosCompra>[];
      v.forEach((v) {
        arr0.add(CosbiomeVentaResponseModelProductosCompra.fromJson(v));
      });
      productosCompra = arr0;
    }
    numTel = json['numTel']?.toString();
    nota = json['nota']?.toString();
    nombreCliente = json['nombreCliente']?.toString();
    metodoDePago = json['metodoDePago']?.toString();
    medio = json['medio']?.toString();
    iva = json['iva']?.toInt();
    idPedido = json['idPedido']?.toString();
    idFirebase = json['idFirebase']?.toString();
    idCliente = json['idCliente']?.toString();
    horaVenta = json['horaVenta']?.toString();
    fechaVenta = json['fechaVenta']?.toString();
    fechaDeEntrega = json['fechaDeEntrega']?.toString();
    direccion = (json['direccion'] != null)
        ? CosbiomeVentaResponseModelDireccion.fromJson(json['direccion'])
        : null;
    de = json['de']?.toString();
    cargo = json['cargo']?.toInt();
    autorizado = json['autorizado']?.toString();
    a = json['a']?.toString();
    pagos = json['pagos']?.toString();
    publishedAt = json['published_at']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    id = json['id']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['abono'] = abono;
    data['apartado'] = apartado;
    data['estatus'] = estatus;
    data['ENVIO'] = ENVIO;
    data['peso'] = peso;
    data['sucursal'] = sucursal;
    data['_id'] = Id;
    data['vendedor'] = vendedor;
    data['total'] = total;
    data['subTotal'] = subTotal;
    data['referencia'] = referencia;
    if (productosCompra != null) {
      final v = productosCompra;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['productosCompra'] = arr0;
    }
    data['numTel'] = numTel;
    data['nota'] = nota;
    data['nombreCliente'] = nombreCliente;
    data['metodoDePago'] = metodoDePago;
    data['medio'] = medio;
    data['iva'] = iva;
    data['idPedido'] = idPedido;
    data['idFirebase'] = idFirebase;
    data['idCliente'] = idCliente;
    data['horaVenta'] = horaVenta;
    data['fechaVenta'] = fechaVenta;
    data['fechaDeEntrega'] = fechaDeEntrega;
    if (direccion != null) {
      data['direccion'] = direccion!.toJson();
    }
    data['de'] = de;
    data['cargo'] = cargo;
    data['autorizado'] = autorizado;
    data['a'] = a;
    data['pagos'] = pagos;
    data['published_at'] = publishedAt;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['id'] = id;
    return data;
  }
}
