///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class LoteEscaneosModelProductoLoteEscaneos {
  /*
{
  "id": 10,
  "documentId": "p8yqeuj81mlaqz3w100we242",
  "createdAt": "2026-02-16T16:16:03.049Z",
  "updatedAt": "2026-02-16T16:16:03.049Z",
  "publishedAt": "2026-02-16T16:16:03.054Z"
} 
*/

  int? id;
  String? documentId;
  String? createdAt;
  String? updatedAt;
  String? publishedAt;

  LoteEscaneosModelProductoLoteEscaneos({
    this.id,
    this.documentId,
    this.createdAt,
    this.updatedAt,
    this.publishedAt,
  });
  LoteEscaneosModelProductoLoteEscaneos.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    documentId = json['documentId']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    publishedAt = json['publishedAt']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['documentId'] = documentId;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['publishedAt'] = publishedAt;
    return data;
  }
}

class LoteEscaneosModelProductoFormula {
  /*
{
  "id": 6,
  "documentId": "stqj135gqbfj82h44kialpi0",
  "nombre": "PRUEBA FORMULA",
  "createdAt": "2026-02-13T19:05:57.878Z",
  "updatedAt": "2026-02-13T19:05:57.878Z",
  "publishedAt": "2026-02-13T19:05:57.887Z"
} 
*/

  int? id;
  String? documentId;
  String? nombre;
  String? createdAt;
  String? updatedAt;
  String? publishedAt;

  LoteEscaneosModelProductoFormula({
    this.id,
    this.documentId,
    this.nombre,
    this.createdAt,
    this.updatedAt,
    this.publishedAt,
  });
  LoteEscaneosModelProductoFormula.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    documentId = json['documentId']?.toString();
    nombre = json['nombre']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    publishedAt = json['publishedAt']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['documentId'] = documentId;
    data['nombre'] = nombre;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['publishedAt'] = publishedAt;
    return data;
  }
}

class LoteEscaneosModelProductoLotes {
  /*
{
  "id": 29,
  "documentId": "dlsoi3qcvrvpruprr9cemfjq",
  "nombre": "asdad",
  "isTerminado": true,
  "terminado": "2026-02-14T09:45:47.402Z",
  "notas": "{\"descripcion\":\"Producción: Prueba 3 PRU: 3 uds\",\"items\":[{\"documentId\":\"s90ipy4unqq9enamqpypi47u\",\"nombre\":\"Prueba 3 PRU\",\"cantidad\":3}],\"enAlmacen\":false,\"notasUsuario\":[{\"insert\":\"PRUEBA\",\"attributes\":{\"bold\":true}},{\"insert\":\"\\n\",\"attributes\":{\"header\":1}},{\"insert\":\"\\nHola, Mundo\"},{\"insert\":\"\\n\",\"attributes\":{\"header\":3}},{\"insert\":\"Adios\"},{\"insert\":\"\\n\",\"attributes\":{\"list\":\"ordered\"}},{\"insert\":\"Mundo\"},{\"insert\":\"\\n\",\"attributes\":{\"list\":\"ordered\"}},{\"insert\":\"\\nESCANEAR PRODUCTOS PRUBA 3 A ETIQUETAS \"},{\"insert\":\"\\n\",\"attributes\":{\"list\":\"checked\"}},{\"insert\":\"ENTREGAR LOTE\"},{\"insert\":\"\\n\",\"attributes\":{\"list\":\"checked\"}}]}",
  "createdAt": "2026-02-13T22:57:00.438Z",
  "updatedAt": "2026-02-14T16:35:38.925Z",
  "publishedAt": "2026-02-14T16:35:38.932Z"
} 
*/

  int? id;
  String? documentId;
  String? nombre;
  bool? isTerminado;
  String? terminado;
  String? notas;
  String? createdAt;
  String? updatedAt;
  String? publishedAt;

  LoteEscaneosModelProductoLotes({
    this.id,
    this.documentId,
    this.nombre,
    this.isTerminado,
    this.terminado,
    this.notas,
    this.createdAt,
    this.updatedAt,
    this.publishedAt,
  });
  LoteEscaneosModelProductoLotes.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    documentId = json['documentId']?.toString();
    nombre = json['nombre']?.toString();
    isTerminado = json['isTerminado'];
    terminado = json['terminado']?.toString();
    notas = json['notas']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    publishedAt = json['publishedAt']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['documentId'] = documentId;
    data['nombre'] = nombre;
    data['isTerminado'] = isTerminado;
    data['terminado'] = terminado;
    data['notas'] = notas;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['publishedAt'] = publishedAt;
    return data;
  }
}

class LoteEscaneosModelProducto {
  /*
{
  "id": 144,
  "documentId": "s90ipy4unqq9enamqpypi47u",
  "nombre": "Prueba 3 PRU",
  "tipo": "GENERAL",
  "fabricacion": 0,
  "terminado": 3,
  "almacen": 0,
  "createdAt": "2026-02-11T18:38:09.669Z",
  "updatedAt": "2026-02-14T16:32:30.779Z",
  "publishedAt": "2026-02-14T16:32:30.785Z",
  "lotes": [
    {
      "id": 29,
      "documentId": "dlsoi3qcvrvpruprr9cemfjq",
      "nombre": "asdad",
      "isTerminado": true,
      "terminado": "2026-02-14T09:45:47.402Z",
      "notas": "{\"descripcion\":\"Producción: Prueba 3 PRU: 3 uds\",\"items\":[{\"documentId\":\"s90ipy4unqq9enamqpypi47u\",\"nombre\":\"Prueba 3 PRU\",\"cantidad\":3}],\"enAlmacen\":false,\"notasUsuario\":[{\"insert\":\"PRUEBA\",\"attributes\":{\"bold\":true}},{\"insert\":\"\\n\",\"attributes\":{\"header\":1}},{\"insert\":\"\\nHola, Mundo\"},{\"insert\":\"\\n\",\"attributes\":{\"header\":3}},{\"insert\":\"Adios\"},{\"insert\":\"\\n\",\"attributes\":{\"list\":\"ordered\"}},{\"insert\":\"Mundo\"},{\"insert\":\"\\n\",\"attributes\":{\"list\":\"ordered\"}},{\"insert\":\"\\nESCANEAR PRODUCTOS PRUBA 3 A ETIQUETAS \"},{\"insert\":\"\\n\",\"attributes\":{\"list\":\"checked\"}},{\"insert\":\"ENTREGAR LOTE\"},{\"insert\":\"\\n\",\"attributes\":{\"list\":\"checked\"}}]}",
      "createdAt": "2026-02-13T22:57:00.438Z",
      "updatedAt": "2026-02-14T16:35:38.925Z",
      "publishedAt": "2026-02-14T16:35:38.932Z"
    }
  ],
  "formula": {
    "id": 6,
    "documentId": "stqj135gqbfj82h44kialpi0",
    "nombre": "PRUEBA FORMULA",
    "createdAt": "2026-02-13T19:05:57.878Z",
    "updatedAt": "2026-02-13T19:05:57.878Z",
    "publishedAt": "2026-02-13T19:05:57.887Z"
  },
  "lote_escaneos": [
    {
      "id": 10,
      "documentId": "p8yqeuj81mlaqz3w100we242",
      "createdAt": "2026-02-16T16:16:03.049Z",
      "updatedAt": "2026-02-16T16:16:03.049Z",
      "publishedAt": "2026-02-16T16:16:03.054Z"
    }
  ]
} 
*/

  int? id;
  String? documentId;
  String? nombre;
  String? tipo;
  int? fabricacion;
  int? terminado;
  int? almacen;
  String? createdAt;
  String? updatedAt;
  String? publishedAt;
  List<LoteEscaneosModelProductoLotes?>? lotes;
  LoteEscaneosModelProductoFormula? formula;
  List<LoteEscaneosModelProductoLoteEscaneos?>? loteEscaneos;

  LoteEscaneosModelProducto({
    this.id,
    this.documentId,
    this.nombre,
    this.tipo,
    this.fabricacion,
    this.terminado,
    this.almacen,
    this.createdAt,
    this.updatedAt,
    this.publishedAt,
    this.lotes,
    this.formula,
    this.loteEscaneos,
  });
  LoteEscaneosModelProducto.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    documentId = json['documentId']?.toString();
    nombre = json['nombre']?.toString();
    tipo = json['tipo']?.toString();
    fabricacion = json['fabricacion']?.toInt();
    terminado = json['terminado']?.toInt();
    almacen = json['almacen']?.toInt();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    publishedAt = json['publishedAt']?.toString();
    if (json['lotes'] != null) {
      final v = json['lotes'];
      final arr0 = <LoteEscaneosModelProductoLotes>[];
      v.forEach((v) {
        arr0.add(LoteEscaneosModelProductoLotes.fromJson(v));
      });
      lotes = arr0;
    }
    formula = (json['formula'] != null)
        ? LoteEscaneosModelProductoFormula.fromJson(json['formula'])
        : null;
    if (json['lote_escaneos'] != null) {
      final v = json['lote_escaneos'];
      final arr0 = <LoteEscaneosModelProductoLoteEscaneos>[];
      v.forEach((v) {
        arr0.add(LoteEscaneosModelProductoLoteEscaneos.fromJson(v));
      });
      loteEscaneos = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['documentId'] = documentId;
    data['nombre'] = nombre;
    data['tipo'] = tipo;
    data['fabricacion'] = fabricacion;
    data['terminado'] = terminado;
    data['almacen'] = almacen;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['publishedAt'] = publishedAt;
    if (lotes != null) {
      final v = lotes;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['lotes'] = arr0;
    }
    if (formula != null) {
      data['formula'] = formula!.toJson();
    }
    if (loteEscaneos != null) {
      final v = loteEscaneos;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['lote_escaneos'] = arr0;
    }
    return data;
  }
}

class LoteEscaneosModel {
  /*
{
  "createdAt": "2026-02-16T16:16:21.044Z",
  "id": 12,
  "documentId": "yirls2ybfchzvsibajg3y4nk",
  "updatedAt": "2026-02-16T16:16:21.044Z",
  "publishedAt": "2026-02-16T16:16:21.048Z",
  "producto": {
    "id": 144,
    "documentId": "s90ipy4unqq9enamqpypi47u",
    "nombre": "Prueba 3 PRU",
    "tipo": "GENERAL",
    "fabricacion": 0,
    "terminado": 3,
    "almacen": 0,
    "createdAt": "2026-02-11T18:38:09.669Z",
    "updatedAt": "2026-02-14T16:32:30.779Z",
    "publishedAt": "2026-02-14T16:32:30.785Z",
    "lotes": [
      {
        "id": 29,
        "documentId": "dlsoi3qcvrvpruprr9cemfjq",
        "nombre": "asdad",
        "isTerminado": true,
        "terminado": "2026-02-14T09:45:47.402Z",
        "notas": "{\"descripcion\":\"Producción: Prueba 3 PRU: 3 uds\",\"items\":[{\"documentId\":\"s90ipy4unqq9enamqpypi47u\",\"nombre\":\"Prueba 3 PRU\",\"cantidad\":3}],\"enAlmacen\":false,\"notasUsuario\":[{\"insert\":\"PRUEBA\",\"attributes\":{\"bold\":true}},{\"insert\":\"\\n\",\"attributes\":{\"header\":1}},{\"insert\":\"\\nHola, Mundo\"},{\"insert\":\"\\n\",\"attributes\":{\"header\":3}},{\"insert\":\"Adios\"},{\"insert\":\"\\n\",\"attributes\":{\"list\":\"ordered\"}},{\"insert\":\"Mundo\"},{\"insert\":\"\\n\",\"attributes\":{\"list\":\"ordered\"}},{\"insert\":\"\\nESCANEAR PRODUCTOS PRUBA 3 A ETIQUETAS \"},{\"insert\":\"\\n\",\"attributes\":{\"list\":\"checked\"}},{\"insert\":\"ENTREGAR LOTE\"},{\"insert\":\"\\n\",\"attributes\":{\"list\":\"checked\"}}]}",
        "createdAt": "2026-02-13T22:57:00.438Z",
        "updatedAt": "2026-02-14T16:35:38.925Z",
        "publishedAt": "2026-02-14T16:35:38.932Z"
      }
    ],
    "formula": {
      "id": 6,
      "documentId": "stqj135gqbfj82h44kialpi0",
      "nombre": "PRUEBA FORMULA",
      "createdAt": "2026-02-13T19:05:57.878Z",
      "updatedAt": "2026-02-13T19:05:57.878Z",
      "publishedAt": "2026-02-13T19:05:57.887Z"
    },
    "lote_escaneos": [
      {
        "id": 10,
        "documentId": "p8yqeuj81mlaqz3w100we242",
        "createdAt": "2026-02-16T16:16:03.049Z",
        "updatedAt": "2026-02-16T16:16:03.049Z",
        "publishedAt": "2026-02-16T16:16:03.054Z"
      }
    ]
  }
} 
*/

  String? createdAt;
  int? id;
  String? documentId;
  String? updatedAt;
  String? publishedAt;
  LoteEscaneosModelProducto? producto;

  LoteEscaneosModel({
    this.createdAt,
    this.id,
    this.documentId,
    this.updatedAt,
    this.publishedAt,
    this.producto,
  });
  LoteEscaneosModel.fromJson(Map<String, dynamic> json) {
    createdAt = json['createdAt']?.toString();
    id = json['id']?.toInt();
    documentId = json['documentId']?.toString();
    updatedAt = json['updatedAt']?.toString();
    publishedAt = json['publishedAt']?.toString();
    producto = (json['producto'] != null)
        ? LoteEscaneosModelProducto.fromJson(json['producto'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['createdAt'] = createdAt;
    data['id'] = id;
    data['documentId'] = documentId;
    data['updatedAt'] = updatedAt;
    data['publishedAt'] = publishedAt;
    if (producto != null) {
      data['producto'] = producto!.toJson();
    }
    return data;
  }
}
