///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ProductoCosbiomeModel {
  /*
{
  "precioProducto": 630,
  "productoApartado": 0,
  "cantidadProducto": 0,
  "general": 5,
  "conteo": 0,
  "enExpo": 14,
  "precioVenta": 756,
  "apartados": 1,
  "enPromo": false,
  "revision": 0,
  "exhibicion": 0,
  "escuela": 0,
  "reparacion": 0,
  "precioContado": 0,
  "precioDoceMeses": 0,
  "pendienteEntrega": 0,
  "_id": "6442a3df0a5aea3cf1bd2204",
  "urlImg": "",
  "nombreProducto": "HIDRALIP BALANCE EMULSION 250 GR EUPEEL",
  "descuentoAplicado": "0 %",
  "s3url": "https://cosbiome.s3.us-east-2.amazonaws.com/maquinas/HIDRALIP BALANCE EMULSION 250 GR EUPEEL/Balance Emulsion Hidralip2.png",
  "categoria": "EUPEEL",
  "codigoProducto": "340CR",
  "imagen": "CREM Y GEL EQUILIBRANT SKIN GRANDE.png",
  "descripcion": "Mezcla perfecta de crema y gel que forma un suave cremygel hidratante, equilibrante del pH y grasasequedad del rostro (especielmente en la zona “T”), mientras reafirma, nutre y disminuye los signos de envejecimiento.",
  "published_at": "2023-04-21T14:55:27.538Z",
  "createdAt": "2023-04-21T14:55:27.543Z",
  "updatedAt": "2025-03-09T00:35:01.399Z",
  "__v": 0,
  "id": "6442a3df0a5aea3cf1bd2204"
} 
*/

  int? precioProducto;
  int? productoApartado;
  int? cantidadProducto;
  int? general;
  int? conteo;
  int? enExpo;
  int? precioVenta;
  int? apartados;
  bool? enPromo;
  int? revision;
  int? exhibicion;
  int? escuela;
  int? reparacion;
  int? precioContado;
  int? precioDoceMeses;
  int? pendienteEntrega;
  String? urlImg;
  String? nombreProducto;
  String? descuentoAplicado;
  String? s3url;
  String? categoria;
  String? codigoProducto;
  String? imagen;
  String? descripcion;
  String? publishedAt;
  String? createdAt;
  String? updatedAt;
  String? id;

  ProductoCosbiomeModel({
    this.precioProducto,
    this.productoApartado,
    this.cantidadProducto,
    this.general,
    this.conteo,
    this.enExpo,
    this.precioVenta,
    this.apartados,
    this.enPromo,
    this.revision,
    this.exhibicion,
    this.escuela,
    this.reparacion,
    this.precioContado,
    this.precioDoceMeses,
    this.pendienteEntrega,
    this.urlImg,
    this.nombreProducto,
    this.descuentoAplicado,
    this.s3url,
    this.categoria,
    this.codigoProducto,
    this.imagen,
    this.descripcion,
    this.publishedAt,
    this.createdAt,
    this.updatedAt,
    this.id,
  });
  ProductoCosbiomeModel.fromJson(Map<String, dynamic> json) {
    precioProducto = json['precioProducto']?.toInt();
    productoApartado = json['productoApartado']?.toInt();
    cantidadProducto = json['cantidadProducto']?.toInt();
    general = json['general']?.toInt();
    conteo = json['conteo']?.toInt();
    enExpo = json['enExpo']?.toInt();
    precioVenta = json['precioVenta']?.toInt();
    apartados = json['apartados']?.toInt();
    enPromo = json['enPromo'];
    revision = json['revision']?.toInt();
    exhibicion = json['exhibicion']?.toInt();
    escuela = json['escuela']?.toInt();
    reparacion = json['reparacion']?.toInt();
    precioContado = json['precioContado']?.toInt();
    precioDoceMeses = json['precioDoceMeses']?.toInt();
    pendienteEntrega = json['pendienteEntrega']?.toInt();
    urlImg = json['urlImg']?.toString();
    nombreProducto = json['nombreProducto']?.toString();
    descuentoAplicado = json['descuentoAplicado']?.toString();
    s3url = json['s3url']?.toString();
    categoria = json['categoria']?.toString();
    codigoProducto = json['codigoProducto']?.toString();
    imagen = json['imagen']?.toString();
    descripcion = json['descripcion']?.toString();
    publishedAt = json['published_at']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();

    id = json['id']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['precioProducto'] = precioProducto;
    data['productoApartado'] = productoApartado;
    data['cantidadProducto'] = cantidadProducto;
    data['general'] = general;
    data['conteo'] = conteo;
    data['enExpo'] = enExpo;
    data['precioVenta'] = precioVenta;
    data['apartados'] = apartados;
    data['enPromo'] = enPromo;
    data['revision'] = revision;
    data['exhibicion'] = exhibicion;
    data['escuela'] = escuela;
    data['reparacion'] = reparacion;
    data['precioContado'] = precioContado;
    data['precioDoceMeses'] = precioDoceMeses;
    data['pendienteEntrega'] = pendienteEntrega;
    data['urlImg'] = urlImg;
    data['nombreProducto'] = nombreProducto;
    data['descuentoAplicado'] = descuentoAplicado;
    data['s3url'] = s3url;
    data['categoria'] = categoria;
    data['codigoProducto'] = codigoProducto;
    data['imagen'] = imagen;
    data['descripcion'] = descripcion;
    data['published_at'] = publishedAt;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;

    data['id'] = id;
    return data;
  }
}
